import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { resetApp, grantTestAccess } from "./helpers";
test("manual appointment validates, persists, exports and completes without demo sync", async ({page}) => {
  await resetApp(page); await grantTestAccess(page); await page.goto("/calendar");
  await expect(page.getByRole("button",{name:"Sync calendars"})).toHaveCount(0);
  await page.getByRole("button",{name:"Add appointment",exact:true}).click();
  await page.getByLabel("Title",{exact:true}).fill("Rural inspection preparation");
  await page.getByLabel("Starts",{exact:true}).fill("2027-03-10T10:00");
  await page.getByLabel("Ends",{exact:true}).fill("2027-03-10T09:00");
  await page.getByRole("button",{name:"Save appointment",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("End time must be after");
  await page.getByLabel("Ends",{exact:true}).fill("2027-03-10T11:00");
  await page.getByRole("textbox",{name:"Preparation notes",exact:true}).fill("Bring the property disclosure documents.");
  await page.getByRole("button",{name:"Save appointment",exact:true}).click();
  await expect(page.getByText("Rural inspection preparation",{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByText("Rural inspection preparation",{exact:true})).toBeVisible();
  await page.screenshot({path:"tmp/session6/calendar-desktop.png",fullPage:true});
  const downloadReady=page.waitForEvent("download");
  await page.getByRole("button",{name:"Export calendar",exact:true}).click();
  const download=await downloadReady;
  expect(download.suggestedFilename()).toBe("appointment.ics");
  expect(await readFile((await download.path())!,"utf8")).toContain("SUMMARY:Rural inspection preparation");
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole("button",{name:"Export calendar",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:"tmp/session6/calendar-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"Done",exact:true}).click();
  await expect(page.getByText("completed",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Delete Rural inspection preparation",exact:true}).click();
  await expect(page.getByText("Your calendar is clear",{exact:true})).toBeVisible();
});
