/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AieoRouteImport } from './routes/aieo'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CmaRouteImport } from './routes/cma'
import { Route as EdgeRouteImport } from './routes/edge'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as MlsRouteImport } from './routes/mls'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TransactionsRouteImport } from './routes/transactions'

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AieoRoute = AieoRouteImport.update({
  id: '/aieo',
  path: '/aieo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CmaRoute = CmaRouteImport.update({
  id: '/cma',
  path: '/cma',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeRoute = EdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MlsRoute = MlsRouteImport.update({
  id: '/mls',
  path: '/mls',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof IndexRoute
  '/aieo': typeof AieoRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/cma': typeof CmaRoute
  '/edge': typeof EdgeRoute
  '/feedback': typeof FeedbackRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/mls': typeof MlsRoute
  '/outreach': typeof OutreachRoute
  '/properties': typeof PropertiesRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof IndexRoute
  '/aieo': typeof AieoRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/cma': typeof CmaRoute
  '/edge': typeof EdgeRoute
  '/feedback': typeof FeedbackRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/mls': typeof MlsRoute
  '/outreach': typeof OutreachRoute
  '/properties': typeof PropertiesRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof IndexRoute
  '/aieo': typeof AieoRoute
  '/alerts': typeof AlertsRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/cma': typeof CmaRoute
  '/edge': typeof EdgeRoute
  '/feedback': typeof FeedbackRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/mls': typeof MlsRoute
  '/outreach': typeof OutreachRoute
  '/properties': typeof PropertiesRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/auth/$'
    | '/'
    | '/aieo'
    | '/alerts'
    | '/billing'
    | '/calendar'
    | '/cma'
    | '/edge'
    | '/feedback'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/market'
    | '/marketing'
    | '/mls'
    | '/outreach'
    | '/properties'
    | '/search'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/auth/$'
    | '/'
    | '/aieo'
    | '/alerts'
    | '/billing'
    | '/calendar'
    | '/cma'
    | '/edge'
    | '/feedback'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/market'
    | '/marketing'
    | '/mls'
    | '/outreach'
    | '/properties'
    | '/search'
    | '/transactions'
  id:
    | '__root__'
    | '/api/auth/$'
    | '/'
    | '/aieo'
    | '/alerts'
    | '/billing'
    | '/calendar'
    | '/cma'
    | '/edge'
    | '/feedback'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/market'
    | '/marketing'
    | '/mls'
    | '/outreach'
    | '/properties'
    | '/search'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IndexRoute: typeof IndexRoute
  AieoRoute: typeof AieoRoute
  AlertsRoute: typeof AlertsRoute
  BillingRoute: typeof BillingRoute
  CalendarRoute: typeof CalendarRoute
  CmaRoute: typeof CmaRoute
  EdgeRoute: typeof EdgeRoute
  FeedbackRoute: typeof FeedbackRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MarketingRoute: typeof MarketingRoute
  MlsRoute: typeof MlsRoute
  OutreachRoute: typeof OutreachRoute
  PropertiesRoute: typeof PropertiesRoute
  SearchRoute: typeof SearchRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aieo': {
      id: '/aieo'
      path: '/aieo'
      fullPath: '/aieo'
      preLoaderRoute: typeof AieoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cma': {
      id: '/cma'
      path: '/cma'
      fullPath: '/cma'
      preLoaderRoute: typeof CmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge': {
      id: '/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof EdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mls': {
      id: '/mls'
      path: '/mls'
      fullPath: '/mls'
      preLoaderRoute: typeof MlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IndexRoute: IndexRoute,
  AieoRoute: AieoRoute,
  AlertsRoute: AlertsRoute,
  BillingRoute: BillingRoute,
  CalendarRoute: CalendarRoute,
  CmaRoute: CmaRoute,
  EdgeRoute: EdgeRoute,
  FeedbackRoute: FeedbackRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MarketingRoute: MarketingRoute,
  MlsRoute: MlsRoute,
  OutreachRoute: OutreachRoute,
  PropertiesRoute: PropertiesRoute,
  SearchRoute: SearchRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
